import fs from "node:fs";
import path from "node:path";

export function validateContract(contract) {
  if (!contract || typeof contract !== "object") throw new Error("Contract must be an object.");
  for (const key of ["name", "version", "tool"]) {
    if (typeof contract[key] !== "string" || !contract[key]) throw new Error(`Contract ${key} is required.`);
  }
  if (!Array.isArray(contract.actions) || contract.actions.length === 0) {
    throw new Error("Contract actions must be a non-empty array.");
  }
  const names = new Set();
  for (const action of contract.actions) {
    if (!action.name || names.has(action.name)) throw new Error(`Duplicate or missing action: ${action.name}`);
    names.add(action.name);
    if (!action.input || !action.output) throw new Error(`Action ${action.name} requires input and output schemas.`);
  }
}

export function generateContract(contract, outputDir) {
  validateContract(contract);
  const files = {
    "node/types.d.ts": generateTypeScript(contract),
    "python/models.py": generatePython(contract),
    "go/types.go": generateGo(contract),
    "fixtures/happy-path.jsonl": generateFixtures(contract),
    "ui/mock.js": generateUiMock(contract),
    "contract-manifest.json": `${JSON.stringify({
      name: contract.name,
      version: contract.version,
      tool: contract.tool,
      actions: contract.actions.map((action) => action.name)
    }, null, 2)}\n`
  };
  for (const [relative, content] of Object.entries(files)) {
    const target = path.join(outputDir, relative);
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, content);
  }
  return files;
}

export function generateTypeScript(contract) {
  const blocks = ["// Generated file. Do not edit.\n"];
  for (const [name, schema] of Object.entries(contract.definitions || {})) {
    blocks.push(tsInterface(name, schema, contract));
  }
  for (const action of contract.actions) {
    const name = pascal(action.name);
    blocks.push(tsInterface(`${name}Input`, action.input, contract));
    blocks.push(`export type ${name}Output = ${tsType(action.output, contract)};\n`);
  }
  blocks.push(`export type ActionName = ${contract.actions.map((item) => JSON.stringify(item.name)).join(" | ")};\n`);
  return `${blocks.join("\n")}\n`;
}

export function generatePython(contract) {
  const blocks = [
    "# Generated file. Do not edit.",
    "from __future__ import annotations",
    "from typing import NotRequired, TypedDict",
    ""
  ];
  for (const [name, schema] of Object.entries(contract.definitions || {})) {
    blocks.push(pyTypedDict(name, schema, contract), "");
  }
  for (const action of contract.actions) {
    blocks.push(pyTypedDict(`${pascal(action.name)}Input`, action.input, contract), "");
    blocks.push(`${pascal(action.name)}Output = ${pyType(action.output, contract)}`, "");
  }
  return `${blocks.join("\n").trim()}\n`;
}

export function generateGo(contract) {
  const blocks = ["// Code generated by anna-contract. DO NOT EDIT.", "package contract", ""];
  for (const [name, schema] of Object.entries(contract.definitions || {})) {
    blocks.push(goStruct(name, schema, contract), "");
  }
  for (const action of contract.actions) {
    const name = pascal(action.name);
    blocks.push(goStruct(`${name}Input`, action.input, contract), "");
    blocks.push(`type ${name}Output = ${goType(action.output, contract)}`, "");
  }
  return `${blocks.join("\n").trim()}\n`;
}

function generateFixtures(contract) {
  return `${contract.actions
    .filter((action) => action.example)
    .map((action, index) => JSON.stringify({
      jsonrpc: "2.0",
      id: index + 1,
      method: "invoke",
      params: {
        tool: contract.tool,
        arguments: { action: action.name, ...action.example.input }
      },
      expected: action.example.output
    }))
    .join("\n")}\n`;
}

function generateUiMock(contract) {
  const examples = Object.fromEntries(contract.actions
    .filter((action) => action.example)
    .map((action) => [action.name, action.example.output]));
  return `// Generated file. Do not edit.\nexport const toolName = ${JSON.stringify(contract.tool)};\nexport const actionExamples = ${JSON.stringify(examples, null, 2)};\n\nexport function mockInvoke(args) {\n  if (!(args.action in actionExamples)) throw new Error(\`Unknown action: \${args.action}\`);\n  return structuredClone(actionExamples[args.action]);\n}\n`;
}

function tsInterface(name, schema, contract) {
  const resolved = resolve(schema, contract);
  if (resolved.type !== "object") return `export type ${name} = ${tsType(schema, contract)};\n`;
  const required = new Set(resolved.required || []);
  const lines = Object.entries(resolved.properties || {}).map(([key, value]) =>
    `  ${safeTsKey(key)}${required.has(key) ? "" : "?"}: ${tsType(value, contract)};`);
  return `export interface ${name} {\n${lines.join("\n")}\n}\n`;
}

function tsType(schema, contract) {
  if (schema.$ref) return refName(schema.$ref);
  const types = Array.isArray(schema.type) ? schema.type : [schema.type || "unknown"];
  return types.map((type) => {
    switch (type) {
      case "string": return "string";
      case "integer":
      case "number": return "number";
      case "boolean": return "boolean";
      case "null": return "null";
      case "object":
        return schema.properties
          ? `{ ${Object.entries(schema.properties).map(([key, value]) => `${safeTsKey(key)}: ${tsType(value, contract)}`).join("; ")} }`
          : "Record<string, unknown>";
      case "array": return `${tsType(schema.items || {}, contract)}[]`;
      default: return "unknown";
    }
  }).join(" | ");
}

function pyTypedDict(name, schema, contract) {
  const resolved = resolve(schema, contract);
  const required = new Set(resolved.required || []);
  const lines = Object.entries(resolved.properties || {}).map(([key, value]) => {
    const type = pyType(value, contract);
    return `    ${key}: ${required.has(key) ? type : `NotRequired[${type}]`}`;
  });
  return `class ${name}(TypedDict):\n${lines.length ? lines.join("\n") : "    pass"}`;
}

function pyType(schema, contract) {
  if (schema.$ref) return refName(schema.$ref);
  const types = Array.isArray(schema.type) ? schema.type : [schema.type || "object"];
  return types.map((type) => {
    switch (type) {
      case "string": return "str";
      case "integer": return "int";
      case "number": return "float";
      case "boolean": return "bool";
      case "null": return "None";
      case "array": return `list[${pyType(schema.items || {}, contract)}]`;
      case "object":
      default: return "dict[str, object]";
    }
  }).join(" | ");
}

function goStruct(name, schema, contract) {
  const resolved = resolve(schema, contract);
  const required = new Set(resolved.required || []);
  const lines = Object.entries(resolved.properties || {}).map(([key, value]) => {
    const optional = !required.has(key);
    const pointer = optional || includesNull(value);
    return `\t${pascal(key)} ${pointer ? "*" : ""}${goType(value, contract)} \`json:"${key}${optional ? ",omitempty" : ""}"\``;
  });
  return `type ${name} struct {\n${lines.join("\n")}\n}`;
}

function goType(schema, contract) {
  if (schema.$ref) return refName(schema.$ref);
  const type = (Array.isArray(schema.type) ? schema.type.find((item) => item !== "null") : schema.type) || "object";
  switch (type) {
    case "string": return "string";
    case "integer": return "int";
    case "number": return "float64";
    case "boolean": return "bool";
    case "array": return `[]${goType(schema.items || {}, contract)}`;
    case "object": return "map[string]any";
    default: return "any";
  }
}

function resolve(schema, contract) {
  return schema.$ref ? contract.definitions[refName(schema.$ref)] : schema;
}

function refName(ref) {
  return ref.split("/").pop();
}

function includesNull(schema) {
  return Array.isArray(schema.type) && schema.type.includes("null");
}

function pascal(value) {
  return String(value).split(/[^A-Za-z0-9]+/).filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1)).join("");
}

function safeTsKey(value) {
  return /^[A-Za-z_$][\w$]*$/.test(value) ? value : JSON.stringify(value);
}
